# Autogenerated wrapper script for cbindgen_jll for armv7l-linux-musleabihf
export cbindgen

JLLWrappers.@generate_wrapper_header("cbindgen")
JLLWrappers.@declare_executable_product(cbindgen)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        cbindgen,
        "bin/cbindgen",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
